title: Tailor-Made Typography
description: A blog about how designer clothing brands use typography
header_text: ""
footer_text: Copyright 2020 Hannah Phillips
header_feature_image: ../uploads/tailor-made-3.png
bannerheight: 20vmax
logo: ../uploads/copy-of-copy-of-t-5.png
favicon: ../uploads/favicon.ico
gridlayout: true
fixednavbar: false
upzoom: true
