title: Tailor-Made Typography
description: A blog about how designer clothing brands use typography
header_text: "Tailor-Made Typography "
footer_text: Copyright 2020 Hannah Phillips
header_feature_image: ../uploads/tailor-made.png
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
